### PR TITLE
DNS functionality added

### PR DESCRIPTION
**Pull request by verdeanSICKAG**
# Version 2.1.0

## New features
- Added the possibility to configure nameservers via the UI

## Following tasks were checked

- [x] Module is coded and structured according to the "Developing guideline for modules" described within the CSK documentation
- [x] All functions/events/parameters are documented within the manifest documentation
- [x] The manifest description of the main CROWN includes main information about the purpose of the module and how to use it in general
- [x] API docu based on the manifest was created and stored within the "docu"-folder of the repository
- [x] Internal LUA code documentation exists for variables and non served functions
- [x] All relevant infos are logged via the SharedLogger 'ModuleLogger'
- [x] Module supports persistent data feature based on 'CSK_Module_PersistentData'
- [x] Module supports user management based on 'CSK_Module_UserManagement'
- [x] No open "ToDos" within the code or at least clearly explained comments why they exist...
- [x] "Version" key in app manifest was updated following semantic versioning (and use '0.x.y' for test / experimental modules which are not yet ready to be officially released)
- [x] Meaningful IDs used for UI elements
- [x] Module was tested on an AppSpace device (at least on SICK AppEngine) with no error message
- [x] README.md is up to date (incl. info of device + firmware the module was tested with)
- [x] CHANGELOG.md is up to date

### CODE REVIEW

**Comment by golluroSICKAG** [comment]
Thx for your contribution!
We will have a look into it asap.
Cheers!

**Comment by golluroSICKAG** [comment]
Hi!
I did a review of your fork and it looks really nice! Thx!

I just found some minor issues and created a pull request to your fork with recommended changes:
https://github.com/verdeanSICKAG/CSK_Module_DeviceNetworkConfig/pull/1

Please check my edits and eventually merge these changes into your fork before I will merge it into our repo. Thx!

**Comment by verdeanSICKAG** [comment]
Hi Roy,
I have adopted your changes. The module can be merged

**Comment by golluroSICKAG** [comment]
Perfect!

As the repository within the CSK organization does not need the project specific files / folders, I removed them within another fork and merged it already here:
https://github.com/SICKAppSpaceCodingStarterKit/CSK_Module_DeviceNetworkConfig/pull/2

I will close this PR now.

Thank you very much for your contribution!

**Pull request closed without merging**
